# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "advantech-fsl"
BBFILE_PATTERN_advantech-fsl = "^${LAYERDIR}/"
BBFILE_PRIORITY_advantech-fsl = "9"
LAYERVERSION_advantech-fsl = "4"
LAYERSERIES_COMPAT_advantech-fsl = "styhead"
